name: Build

on: [push]

jobs:
  BuildJob:
    name: Build
    runs-on: macos-latest
    steps:
      - shell: bash
        run: |
          git clone https://github.com/ElectroBoy404NotFound/TinyiOS
          cd TinyiOS
          rm -rf newlib
          git clone https://github.com/checkra1n/newlib.git
          sed -i '' "s/-Werror //" Makefile
          make -j$(sysctl -n hw.logicalcpu)
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: TinyiOS
          path: TinyiOS/build/Pongo.bin
